[project]
name = "reinstorm"
version = "0.1.0"
description = "A simple harness for me"
authors = [
    { name = "Matt", email = "matthew.restine@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.143.0",
    "ollama>=0.6.3",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
reinstorm = "reinstorm:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
